application_name: "api-ptf-core-business-orchestrator-ms"
description: "Core Business Orchestrator Microservice for PTF"
application_version: "1.0.0"
entity_uuid: ""  # Generate a new UUID or keep empty for now
environment: "dev"

# Logging configuration
log:
  level: "DEBUG"
  development: true  # Enable development mode (colored output, etc.)

# HTTP server configuration
http:
  port: "8080"
  base_path: "/api/business-orchestrator/v1/"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# Application specific configuration
app:
  # MongoDB configuration
  mongodb:
    uri: "${MONGO_URI:mongodb://localhost:27017}"
    database: "${MONGO_DATABASE:business_orchestrator}"
    timeout: "10s"
  
  # Security
  jwt_secret: "${JWT_SECRET:your-secret-key}"
  password_salt_rounds: 10
  
  # External services
  external_services:
    timeout: "30s"
    max_retries: 3
    retry_delay: "1s"
  
  # Feature flags
  features:
    enable_metrics: true
    enable_tracing: true
    maintenance_mode: false

# Observability
observability:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
  tracing:
    enabled: true
    service_name: "business-orchestrator"
    collector_endpoint: ""  # e.g., "jaeger:14268/api/traces"
  
# Health check configuration
health:
  path: "/health"
  check_interval: "30s"
  timeout: "5s"

# Rate limiting
rate_limit:
  enabled: true
  rps: 100  # requests per second
  burst: 50

# CORS configuration
cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
  exposed_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 300  # seconds

# Timeouts
timeouts:
  database: "10s"
  http_client: "30s"
  grpc_client: "15s"
  shutdown: "30s"
